"""empty message

Revision ID: bc02cd140354
Revises: 45d673741bf9
Create Date: 2021-11-30 03:42:38.972453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc02cd140354'
down_revision = '45d673741bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penduser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=21), nullable=True),
    sa.Column('email', sa.String(length=112), nullable=True),
    sa.Column('password', sa.String(length=211), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penduser')
    # ### end Alembic commands ###
